<?php //ar.viarural.com
	$_host_ = "192.168.4.198";
	$_user_ = "uv9432";
	$_clave_ = "log271828182napier";
	$_sql_dban_ = "uv9432_aranuncios";
	$_sql_dbcl_ = "uv9432_arclasificados";
	$mipais  = "Argentina";
	$miweb  = "www.viarural.com.ar";
	$redirect = "http://www.viarural.com.ar/viarural.com.ar/formulario/gracias.htm";
	$webusuarios = "ar.viarural.com";
	$links = array ("Acoplados" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/acoplados/default.htm",
							"Acoplados Tanque" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/acoplados-tanques/default.htm",
							"Arados" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Autoelevadores" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/autoelevadores/default.htm",
							"Bombas" => "http://www.viarural.com.ar/viarural.com.ar/agroindustria/maquinaria/bombas.htm",
							"Cabezales para Cosechadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/cosechadoras/default.htm",
							"Camiones" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/ganaderos/camiones/default.htm",
							"Cargadoras sobre neumáticos" => "http://www.viarural.com.ar/viarural.com.ar/construccion/cargadoras-sobre-neumaticos/default.htm",
							"Carretones" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/acoplados-tanques/default.htm",
							"Carretones viales" => "http://www.viarural.com.ar/viarural.com.ar/construccion/carretones-viales/default.htms",
							"Casillas Rurales" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/casillasrurales/default.htm",
							"Chimango" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/clasificadoras/fabrinor/chimango.htm",
							"Cinceles" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Cosechadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/cosechadoras/default.htm",
							"Cultivadores" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Desmalezadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/sembradoras/default.htm",
							"Embolsadoras - Embutidoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/embolsadoragranos/default.htm",
							"Escardillos" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/semillashibridas/default.htm",
							"Extractores de Silos" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/extractoresdesilos/default.htm",
							"Fertilizadora" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/sembradoras/default.htm",
							"Grupos Electrógenos" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/ganaderos/motores/default-grupos.htm",
							"Hileradora" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/tractores/default.htm",
							"Hormigoneras - Vibradores" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/ganaderos/motosierras/default.htm",
							"Hoyadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/ganaderos/motosierras/default.htm",
							"Maquinaria Vial" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/maquinariavial/default.htm",
							"Mezcladoras - Moledoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/mezcladoras/default.htm",
							"Minicargadoras" => "http://www.viarural.com.ar/viarural.com.ar/construccion/minicargadoras/default.htm",
							"Miniexcavadoras" => "http://www.viarural.com.ar/viarural.com.ar/construccion/miniexcavadoras/default.htm",
							"Mixers" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/mixers/default.htm",
							"Motoniveladoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/maquinariavial/default.htm",
							"Motores - Grupos Electrógenos" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/tractores/agco-allis/motores/default.htm",
							"Niveladoras" => "http://www.viarural.com.ar/viarural.com.ar/construccion/niveladoras/default.htm",
							"Palas Cargadoras Frontales" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/cargadoresfrontalesyotras/default.htm",
							"Palas Cargadoras Invertidas" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/cargadoresfrontalesyotras/default.htm",
							"Palas de Arrastre" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Picadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/maqforrajeras/default.htm",
							"Plataformas" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/ganaderos/construccionesrurales/default.htm",
							"Pulverizadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/fertilizadoras/default.htm",
							"Rastras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Rastrillos" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/arados/default.htm",
							"Retroexcavadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/cargadoresfrontalesyotras/default.htm",
							"Rotoenfardadoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/maqforrajeras/default.htm",
							"Sembradoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/sembradoras/default.htm",
							"Tanques" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/tanques/default.htm",
							"Topadoras" => "http://www.viarural.com.ar/viarural.com.ar/construccion/topadoras-bulldozer/default.htm",
							"Tractoelevadores" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/sembradoras/default.htm",
							"Tractores" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/tractores/default.htm",
							"Trituradoras" => "http://www.viarural.com.ar/viarural.com.ar/insumosagropecuarios/agricolas/maquinariavial/default.htm",
							"Zanjadoras" => "http://www.viarural.com.ar/viarural.com.ar/construccion/zanjadoras/default.htm" //ok
							);
?>